name: CI

on:
  push:
    branches: ['main']
    paths:
      - 'node/*'
      - 'node/**/*'
      - '.github/workflows/ci.yaml'
  pull_request:
    branches: ['main']
    paths:
      - 'node/*'
      - 'node/**/*'
      - '.github/workflows/ci.yaml'
jobs:
  validate-node:
    name: 'Validate'
    uses: curium-rocks/flows/.github/workflows/node-ts.yml@main
    permissions:
      contents: read
      actions: read
      security-events: write
    with:
      continue-on-prod-vulns: true
      node_versions: '["20.x"]'
      working-dir: 'node/'
      sonar-enabled: false
  publish-docs:
    needs:
      - validate-node
    uses: curium-rocks/flows/.github/workflows/npm-publish-docs.yml@main
    with:
      publish: true
      node_version: '22.x'
      build_task: 'build:docs'
      path: 'docs'
      working_dir: 'node'
